#    This file is part of KSP Tools
#    © 2020 LisiasT
#
#    KSP Tools is licensed as follows:
#
#        * GPL 2.0 : https://www.gnu.org/licenses/gpl-2.0.txt
#
#    KSP Tools is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#    You should have received a copy of the GNU General Public License 2.0
#    along with KSP Tools, if not see <https://www.gnu.org/licenses/>.
#
'''
Created on Sep 27, 2020

@author: lisias
'''

MODULES = set([
	"CModuleFuelLine",
	"CModuleLinkedMesh",
	"CModuleStrut",
	"FXModuleAnimateRCS",
	"FXModuleAnimateThrottle",
	"FXModuleConstrainPosition",
	"FXModuleLookAtConstraint",
	"FlagDecal",
	"FlagDecalBackground",
	"FlagSite",
	"KerbalEVA",
	"KerbalSeat",
	"LaunchClamp",
	"ModuleAblator",
	"ModuleActiveRadiator",
	"ModuleAeroSurface",
	"ModuleAlternator",
	"ModuleAnalysisResource",
	"ModuleAnchoredDecoupler",
	"ModuleAnimateGeneric",
	"ModuleAnimateHeat",
	"ModuleAnimationGroup",
	"ModuleAsteroid",
	"ModuleAsteroidAnalysis",
	"ModuleAsteroidDrill",
	"ModuleAsteroidInfo",
	"ModuleAsteroidResource",
	"ModuleBiomeScanner",
	"ModuleCargoBay",
	"ModuleColorChanger",
	"ModuleComet",
	"ModuleCometAnalysis",
	"ModuleCometDrill",
	"ModuleCometInfo",
	"ModuleCometResource",
	"ModuleCommand",
	"ModuleConductionMultiplier",
	"ModuleControlSurface",
	"ModuleCoreHeat",
	"ModuleDataTransmitter",
	"ModuleDecouple",
	"ModuleDeployableAntenna",
	"ModuleDeployablePart",
	"ModuleDeployableRadiator",
	"ModuleDeployableSolarPanel",
	"ModuleDockingNode",
	"ModuleDragModifier",
	"ModuleDynamicNodes",          # Not used by Stock, but by MH & Serenity
	"ModuleEngines",
	"ModuleEnginesFX",
	"ModuleEnviroSensor",
	"ModuleEvaChute",
	"ModuleExperienceManagement",
	"ModuleFuelJettison",
	"ModuleGPS",
	"ModuleGenerator",
	"ModuleGimbal",
	"ModuleGrappleNode",
	"ModuleInventoryPart",
	"ModuleJettison",
	"ModuleKerbNetAccess",
	"ModuleLiftingSurface",
	"ModuleLight",
	"ModuleMirrorPlacement",       # Not used by Stock, but by MH & Serenity
	"ModuleOrbitalScanner",
	"ModuleOrbitalSurveyor",
	"ModuleOverheatDisplay",
	"ModuleParachute",
	"ModulePartVariants",
	"ModuleProbeControlPoint",
	"ModuleProceduralFairing",
	"ModuleRCSFX",
	"ModuleReactionWheel",
	"ModuleResourceConverter",
	"ModuleResourceDrain",
	"ModuleResourceHarvester",
	"ModuleResourceIntake",
	"ModuleResourceScanner",
	"ModuleSAS",
	"ModuleScienceContainer",
	"ModuleScienceConverter",
	"ModuleScienceExperiment",
	"ModuleScienceLab",
	"ModuleSeeThroughObject",
	"ModuleStatusLight",
	"ModuleStructuralNode",
	"ModuleStructuralNodeToggle",
	"ModuleSurfaceFX",
	"ModuleTestSubject",
	"ModuleToggleCrossfeed",
	"ModuleTripLogger",
	"ModuleWheelBase",
	"ModuleWheelBogey",
	"ModuleWheelBrakes",
	"ModuleWheelDamage",
	"ModuleWheelDeployment",
	"ModuleWheelLock",
	"ModuleWheelMotor",
	"ModuleWheelMotorSteering",
	"ModuleWheelSteering",
	"ModuleWheelSuspension",
	"MultiModeEngine",
	"RetractableLadder",
	"SentinelModule",
])

