#!/usr/bin/env python
# encoding: utf-8
#    This file is part of KSP Tools
#    © 2018 LisiasT
#
#    KSP Tools is licensed as follows:
#
#        * GPL 2.0 : https://www.gnu.org/licenses/gpl-2.0.txt
#
#    KSP Tools is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#    You should have received a copy of the GNU General Public License 2.0
#    along with KSP Tools, if not see <https://www.gnu.org/licenses/>.
#
'''
jsonlint -- Checks for obvious errors on json files.

@author:     Lisias

@copyright:  2018 L Aerospace/KSP Division

@license:    GPL 2.0
'''

import sys
import os
import json

from optparse import OptionParser

__all__ = []
__version__ = 0.1
__date__ = '2018-10-09'
__updated__ = '2020-09-27'

DEBUG = 0
TESTRUN = 0
PROFILE = 0

def run(opts, args):
	dirName = os.path.expanduser(args[0])
	print(dirName)
	listOfFiles = list()
	for (dirpath, dirnames, filenames) in os.walk(dirName):
		listOfFiles += [os.path.join(dirpath, file) for file in filenames if file.endswith('.version')]
	for f in listOfFiles:
		try:
			with open(f) as fp:
				j = json.load(fp)
		except:
			print("BAD :" + f, file=sys.stderr)

def main(argv=None):
	'''Command line options.'''

	program_name = os.path.basename(sys.argv[0])
	program_version = "v0.1"
	program_build_date = "%s" % __updated__

	program_version_string = '%%prog %s (%s)' % (program_version, program_build_date)
	#program_usage = '''usage: spam two eggs''' # optional - will be autogenerated by optparse
	program_longdesc = '''''' # optional - give further explanation about what the program does
	program_license = "Copyright 2018 Lisias (L Aerospace/KSP Division)                                            \
				Licensed under the GPL 2.0\nhttps://www.gnu.org/licenses/old-licenses/gpl-2.0.html"

	if argv is None:
		argv = sys.argv[1:]
	try:
		# setup option parser
		parser = OptionParser(version=program_version_string, epilog=program_longdesc, description=program_license)
		parser.add_option("-i", "--in", dest="infile", help="set input path [default: %default]", metavar="FILE")
		parser.add_option("-o", "--out", dest="outfile", help="set output path [default: %default]", metavar="FILE")
		parser.add_option("-v", "--verbose", dest="verbose", action="count", help="set verbosity level [default: %default]")

		# set defaults
		parser.set_defaults(outfile="./out.txt", infile="./in.txt", verbose=0)

		# process options
		(opts, args) = parser.parse_args(argv)

		if opts.verbose > 0:
			print("verbosity level = %d" % opts.verbose)
			if opts.infile:
				print("infile = %s" % opts.infile)
			if opts.outfile:
				print("outfile = %s" % opts.outfile)

		run(opts, args)

	except Exception as e:
		indent = len(program_name) * " "
		sys.stderr.write(program_name + ": " + repr(e) + "\n")
		sys.stderr.write(indent + "  for help use --help")
		return 2


if __name__ == "__main__":
	if DEBUG:
		sys.argv.append("-h")
	if TESTRUN:
		import doctest
		doctest.testmod()
	if PROFILE:
		import cProfile
		import pstats
		profile_filename = 'jsonlint_profile.txt'
		cProfile.run('main()', profile_filename)
		statsfile = open("profile_stats.txt", "wb")
		p = pstats.Stats(profile_filename, stream=statsfile)
		stats = p.strip_dirs().sort_stats('cumulative')
		stats.print_stats()
		statsfile.close()
		sys.exit(0)
	sys.exit(main())
